//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 02:21:00 PM MSK 
//


package ru.korus.tmis.pdm.service.impl.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.korus.tmis.pdm.service.impl.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.korus.tmis.pdm.service.impl.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PdmConfig }
     * 
     */
    public PdmConfig createPdmConfig() {
        return new PdmConfig();
    }

    /**
     * Create an instance of {@link PdmConfig.Files }
     * 
     */
    public PdmConfig.Files createPdmConfigFiles() {
        return new PdmConfig.Files();
    }

    /**
     * Create an instance of {@link PdmConfig.Docs }
     * 
     */
    public PdmConfig.Docs createPdmConfigDocs() {
        return new PdmConfig.Docs();
    }

    /**
     * Create an instance of {@link PdmConfig.Docs.Doc }
     * 
     */
    public PdmConfig.Docs.Doc createPdmConfigDocsDoc() {
        return new PdmConfig.Docs.Doc();
    }

    /**
     * Create an instance of {@link PdmConfig.Systems }
     * 
     */
    public PdmConfig.Systems createPdmConfigSystems() {
        return new PdmConfig.Systems();
    }

    /**
     * Create an instance of {@link PdmConfig.Admin }
     * 
     */
    public PdmConfig.Admin createPdmConfigAdmin() {
        return new PdmConfig.Admin();
    }

    /**
     * Create an instance of {@link PdmConfig.Files.File }
     * 
     */
    public PdmConfig.Files.File createPdmConfigFilesFile() {
        return new PdmConfig.Files.File();
    }

    /**
     * Create an instance of {@link PdmConfig.Docs.Doc.Attribute }
     * 
     */
    public PdmConfig.Docs.Doc.Attribute createPdmConfigDocsDocAttribute() {
        return new PdmConfig.Docs.Doc.Attribute();
    }

    /**
     * Create an instance of {@link PdmConfig.Systems.System }
     * 
     */
    public PdmConfig.Systems.System createPdmConfigSystemsSystem() {
        return new PdmConfig.Systems.System();
    }

}
